import type { HashKeyAliases } from "../HashStateProvider";

export const SCENE_VIEW_STATE_HASH_KEYS = {
  LATITUDE: "lat",
  LONGITUDE: "lng",
  ZOOM: "zoom",
  ALTITUDE: "altitude",
  BEARING: "bearing",
  PITCH: "pitch",
  ROLL: "roll",
  FOV: "fov",
} as const;

export const SCENE_VIEW_STATE_HASH_KEY_ALIASES: HashKeyAliases = {
  [SCENE_VIEW_STATE_HASH_KEYS.BEARING]: "b",
  [SCENE_VIEW_STATE_HASH_KEYS.PITCH]: "p",
  [SCENE_VIEW_STATE_HASH_KEYS.ROLL]: "r",
  [SCENE_VIEW_STATE_HASH_KEYS.ALTITUDE]: "h",
};

export const SCENE_VIEW_STATE_HASH_KEY_ORDER: string[] = [
  SCENE_VIEW_STATE_HASH_KEYS.LATITUDE,
  SCENE_VIEW_STATE_HASH_KEYS.LONGITUDE,
  SCENE_VIEW_STATE_HASH_KEYS.ZOOM,
  SCENE_VIEW_STATE_HASH_KEY_ALIASES[SCENE_VIEW_STATE_HASH_KEYS.BEARING],
  SCENE_VIEW_STATE_HASH_KEY_ALIASES[SCENE_VIEW_STATE_HASH_KEYS.PITCH],
  SCENE_VIEW_STATE_HASH_KEY_ALIASES[SCENE_VIEW_STATE_HASH_KEYS.ROLL],
  SCENE_VIEW_STATE_HASH_KEY_ALIASES[SCENE_VIEW_STATE_HASH_KEYS.ALTITUDE],
  SCENE_VIEW_STATE_HASH_KEYS.FOV,
];
