import type { StateKeyToHashParamNameAliases } from "../HashStateProvider";

export const SCENE_VIEW_STATE_HASH_PARAM_NAMES = {
  LATITUDE: "lat",
  LONGITUDE: "lng",
  ZOOM: "zoom",
  ALTITUDE: "altitude",
  BEARING: "bearing",
  PITCH: "pitch",
  ROLL: "roll",
  FOV: "fov",
} as const;

export const SCENE_VIEW_STATE_STATE_KEY_TO_HASH_PARAM_NAME_ALIASES: StateKeyToHashParamNameAliases =
  {
    [SCENE_VIEW_STATE_HASH_PARAM_NAMES.BEARING]: "b",
    [SCENE_VIEW_STATE_HASH_PARAM_NAMES.PITCH]: "p",
    [SCENE_VIEW_STATE_HASH_PARAM_NAMES.ROLL]: "r",
    [SCENE_VIEW_STATE_HASH_PARAM_NAMES.ALTITUDE]: "h",
  };

export const SCENE_VIEW_STATE_HASH_PARAM_NAME_ORDER: string[] = [
  SCENE_VIEW_STATE_HASH_PARAM_NAMES.LATITUDE,
  SCENE_VIEW_STATE_HASH_PARAM_NAMES.LONGITUDE,
  SCENE_VIEW_STATE_HASH_PARAM_NAMES.ZOOM,
  SCENE_VIEW_STATE_STATE_KEY_TO_HASH_PARAM_NAME_ALIASES[
    SCENE_VIEW_STATE_HASH_PARAM_NAMES.BEARING
  ],
  SCENE_VIEW_STATE_STATE_KEY_TO_HASH_PARAM_NAME_ALIASES[
    SCENE_VIEW_STATE_HASH_PARAM_NAMES.PITCH
  ],
  SCENE_VIEW_STATE_STATE_KEY_TO_HASH_PARAM_NAME_ALIASES[
    SCENE_VIEW_STATE_HASH_PARAM_NAMES.ROLL
  ],
  SCENE_VIEW_STATE_STATE_KEY_TO_HASH_PARAM_NAME_ALIASES[
    SCENE_VIEW_STATE_HASH_PARAM_NAMES.ALTITUDE
  ],
  SCENE_VIEW_STATE_HASH_PARAM_NAMES.FOV,
];
