import type { GeoreferencedLandmark } from "../base/landmarks";

/** Evidence snapshot, not a claim of live tile availability or surveyed geometry. */
export const LANGENBERG_LANDMARK_PROVENANCE = {
  capturedAt: "2026-09-14T13:21:23Z",
  positionCapturedAt: "2026-09-14T13:20:46Z",
  positionSourceUrl:
    "https://api.openstreetmap.org/api/0.6/map.json?bbox=7.130,51.349,7.140,51.358",
  mappedDataAttribution: "© OpenStreetMap contributors",
  mappedDataLicenseUrl: "https://www.openstreetmap.org/copyright",
  groundDataAttribution: "Geobasis NRW",
  groundDataLicenseUrl: "https://www.govdata.de/dl-de/zero-2-0",
  groundDataDocumentationUrl:
    "https://www.bezreg-koeln.nrw.de/geobasis-nrw/produkte-und-dienste/hoehenmodelle/digitale-gelaendemodelle/digitales-gelaendemodell",
  groundGridSpacingMeters: 1,
  coverage: {
    sourceUrl: "https://terrain.cismet.de/nrw/coverage.geojson",
    checkedAt: "2026-09-14T13:20:46Z",
    method: "point-in-published-polygon-with-holes",
    landmarkIdsInside: ["langenberg-hordt", "langenberg-rommel"],
  },
  modelAccuracy:
    "Mapped guyed lattice masts approximated by opaque axial shells. Widths, intermediate heights and bands are illustrative; no guy-wire geometry or survey accuracy is claimed.",
} as const;

/** Two masts at one transmitter site; both inside the published terrain polygon. */
export const LANGENBERG_LANDMARKS = [
  {
    id: "langenberg-hordt",
    name: "WDR Sender Langenberg · Hordtmast",
    longitudeDegrees: 7.13413305,
    latitudeDegrees: 51.3562576,
    heightMeters: 301,
    groundNormalHeightMeters: 239.25,
    positionEvidence: {
      status: "mapped-not-surveyed",
      sourceUrl: "https://www.openstreetmap.org/way/158358772",
      osmVersion: 6,
      osmEditedAt: "2023-03-25T19:18:04Z",
      method: "way-bounds-center",
    },
    heightEvidence: {
      status: "municipality-published",
      sourceUrl:
        "https://stadtmarketing.velbert.de/tourismus/geschichte-erleben",
    },
    groundEvidence: {
      status: "approximate-terrain",
      source: "nrw-dgm1-wcs",
      verticalDatum: "DHHN2016",
      horizontalCrs: "EPSG:25832",
      sampleMethod: "containing-1m-pixel-center",
      requestBoundsUtm32Meters: [370078, 5691090, 370088, 5691100],
      sampleCenterUtm32Meters: [370083.5, 5691095.5],
      sourceUrl:
        "https://www.wcs.nrw.de/geobasis/wcs_nw_dgm?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=nw_dgm&FORMAT=image%2Ftiff&SUBSET=x%28370078%2C370088%29&SUBSET=y%285691090%2C5691100%29",
    },
    geometryEvidence: "authored-approximate-silhouette",
    parts: [
      {
        baseHeightMeters: 0,
        heightMeters: 50,
        radiusBottomMeters: 1.7,
        radiusTopMeters: 1.7,
        radialSegments: 4,
        color: "#b7443c",
      },
      {
        baseHeightMeters: 50,
        heightMeters: 50,
        radiusBottomMeters: 1.7,
        radiusTopMeters: 1.7,
        radialSegments: 4,
        color: "#e6e4da",
      },
      {
        baseHeightMeters: 100,
        heightMeters: 50,
        radiusBottomMeters: 1.7,
        radiusTopMeters: 1.7,
        radialSegments: 4,
        color: "#b7443c",
      },
      {
        baseHeightMeters: 150,
        heightMeters: 50,
        radiusBottomMeters: 1.7,
        radiusTopMeters: 1.7,
        radialSegments: 4,
        color: "#e6e4da",
      },
      {
        baseHeightMeters: 200,
        heightMeters: 50,
        radiusBottomMeters: 1.7,
        radiusTopMeters: 1.7,
        radialSegments: 4,
        color: "#b7443c",
      },
      {
        baseHeightMeters: 250,
        heightMeters: 12.75,
        radiusBottomMeters: 1.05,
        radiusTopMeters: 0.95,
        radialSegments: 12,
        color: "#e6e4da",
      },
      {
        baseHeightMeters: 262.75,
        heightMeters: 12.75,
        radiusBottomMeters: 0.95,
        radiusTopMeters: 0.85,
        radialSegments: 12,
        color: "#b7443c",
      },
      {
        baseHeightMeters: 275.5,
        heightMeters: 12.75,
        radiusBottomMeters: 0.85,
        radiusTopMeters: 0.75,
        radialSegments: 12,
        color: "#e6e4da",
      },
      {
        baseHeightMeters: 288.25,
        heightMeters: 12.75,
        radiusBottomMeters: 0.75,
        radiusTopMeters: 0.65,
        radialSegments: 12,
        color: "#b7443c",
      },
    ],
  },
  {
    id: "langenberg-rommel",
    name: "WDR Sender Langenberg · Rommelmast",
    longitudeDegrees: 7.1383174,
    latitudeDegrees: 51.3510799,
    heightMeters: 170,
    groundNormalHeightMeters: 246.23,
    positionEvidence: {
      status: "mapped-not-surveyed",
      sourceUrl: "https://www.openstreetmap.org/way/158358778",
      osmVersion: 9,
      osmEditedAt: "2023-05-05T18:38:36Z",
      method: "way-bounds-center",
    },
    heightEvidence: {
      status: "mapped",
      sourceUrl: "https://www.openstreetmap.org/way/158358778",
    },
    groundEvidence: {
      status: "approximate-terrain",
      source: "nrw-dgm1-wcs",
      verticalDatum: "DHHN2016",
      horizontalCrs: "EPSG:25832",
      sampleMethod: "containing-1m-pixel-center",
      requestBoundsUtm32Meters: [370354, 5690507, 370364, 5690517],
      sampleCenterUtm32Meters: [370359.5, 5690512.5],
      sourceUrl:
        "https://www.wcs.nrw.de/geobasis/wcs_nw_dgm?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=nw_dgm&FORMAT=image%2Ftiff&SUBSET=x%28370354%2C370364%29&SUBSET=y%285690507%2C5690517%29",
    },
    geometryEvidence: "authored-approximate-silhouette",
    parts: [
      {
        baseHeightMeters: 0,
        heightMeters: 35,
        radiusBottomMeters: 1.4,
        radiusTopMeters: 1.4,
        radialSegments: 4,
        color: "#b7443c",
      },
      {
        baseHeightMeters: 35,
        heightMeters: 35,
        radiusBottomMeters: 1.4,
        radiusTopMeters: 1.4,
        radialSegments: 4,
        color: "#e6e4da",
      },
      {
        baseHeightMeters: 70,
        heightMeters: 35,
        radiusBottomMeters: 1.4,
        radiusTopMeters: 1.4,
        radialSegments: 4,
        color: "#b7443c",
      },
      {
        baseHeightMeters: 105,
        heightMeters: 35,
        radiusBottomMeters: 1.4,
        radiusTopMeters: 1.4,
        radialSegments: 4,
        color: "#e6e4da",
      },
      {
        baseHeightMeters: 140,
        heightMeters: 15,
        radiusBottomMeters: 0.9,
        radiusTopMeters: 0.7,
        radialSegments: 12,
        color: "#b7443c",
      },
      {
        baseHeightMeters: 155,
        heightMeters: 15,
        radiusBottomMeters: 0.7,
        radiusTopMeters: 0.5,
        radialSegments: 12,
        color: "#e6e4da",
      },
    ],
  },
] as const satisfies readonly GeoreferencedLandmark[];
