export {
  ANNOTATION_ENGINE_KINDS,
  ANNOTATION_ENGINE_POINT_QUERY_INPUT_MODIFIERS,
  ANNOTATION_GIZMO_DISC_SCALING_MODES,
  ANNOTATION_POINT_QUERY_CLICK_STRATEGY,
  ANNOTATION_RING_MATERIAL_PRESETS,
  ANNOTATION_SCENE_POLYGON_FILL_PLACEMENT,
} from "./annotation-engine.types";
export type {
  AnnotationClientPosition,
  AnnotationEngine,
  AnnotationEngineCapabilities,
  AnnotationEngineCoordinateSample,
  AnnotationEngineHooks,
  AnnotationEngineKind,
  AnnotationEnginePointer,
  AnnotationEnginePointQueryInputModifier,
  AnnotationFlyToOptions,
  AnnotationGizmoAxisCandidate,
  AnnotationGizmoDiscScalingMode,
  AnnotationGizmoLabels,
  AnnotationGizmoPoint,
  AnnotationGizmoRotationDelta,
  AnnotationPickRay,
  AnnotationPointMoveGizmoOptions,
  AnnotationPointQueryClickStrategy,
  AnnotationPointQueryConfig,
  AnnotationPointQueryCreatePayload,
  AnnotationPointQueryOptions,
  AnnotationProjectionOptions,
  AnnotationProjectionSnapshot,
  AnnotationProjectionState,
  AnnotationRingMaterialPreset,
  AnnotationSceneDiscOptions,
  AnnotationSceneLineCollection,
  AnnotationSceneLineCollectionOptions,
  AnnotationSceneLineHandle,
  AnnotationSceneLineOptions,
  AnnotationSceneLineStyle,
  AnnotationScenePolygonFill,
  AnnotationScenePolygonFillPlacement,
  AnnotationScenePolygonFillsHandle,
  AnnotationScenePolygonFillsOptions,
  AnnotationScenePrimitiveHandle,
  AnnotationSceneRingOptions,
  AnnotationScreenPosition,
  AnnotationSurfacePick,
  AnnotationSurfacePickOptions,
} from "./annotation-engine.types";
export {
  areAnnotationProjectionSnapshotsEqual,
  isValidAnnotationEngine,
} from "./annotation-engine.helpers";
export {
  ANNOTATION_POINTER_QUERY_PRESERVE_ATTRIBUTE,
  createCanvasPointerTracker,
} from "./canvas-pointer-tracker";
export {
  DEFAULT_POINT_QUERY_CONFIG,
  getScreenPositionDistance,
  isScreenPositionWithinDistance,
  resolvePointQueryConfig,
} from "./point-query-helpers";
export { useEnginePointQuery } from "./use-engine-point-query";
export {
  applyCssForward,
  applyCssInverse,
  buildEngineCssViewMatrix,
  createEngineRotationAxisVisualizer,
  getAxisParamFromClientPosition,
  getAxisSampleWorldStep,
  getGroundPointFromClientPosition,
  getPlaneAngleFromClientPosition,
  getPlanePixelsPerWorldMax,
  getPlanePointFromClientPosition,
  projectPlaneOutlinePoints,
  rotateVectorByVersor,
  useEnginePointMoveGizmo,
} from "./gizmo";
export type {
  BuildEngineCssViewMatrixOptions,
  CssMatrix2,
  EngineCssViewMatrixResult,
  EngineRotationAxisVisualizer,
  EngineRotationAxisVisualizerOptions,
  PlaneBasis,
  ScreenPoint2,
} from "./gizmo";
