import dayjs from "dayjs";

// ---------------------------------------------------------------------------
// Source-layer → server FK field mapping
// ---------------------------------------------------------------------------

/** Maps the vector-tile source layer name to the FK field on arbeitsprotokoll. */
const SOURCE_LAYER_TO_FK: Record<string, string> = {
  leuchten: "fk_leuchte",
  standorte: "fk_standort",
  leitungen: "fk_leitung",
  schaltstelle: "fk_schaltstelle",
  abzweigdosen: "fk_abzweigdose",
  mauerlaschen: "fk_mauerlasche",
};

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Minimal feature shape needed for AA creation. */
export interface AAFeatureInput {
  sourceLayer?: string;
  properties?: Record<string, unknown>;
}

export interface NewAAInput {
  /** Team FK object */
  team: { id: number; name?: string };
  /** Username of the creator */
  angelegtVon: string;
  /** Highlighted features from the Fachobjekte map */
  features: AAFeatureInput[];
  /** Optional AA nummer (auto-generated by server if omitted) */
  nummer?: string;
}

// ---------------------------------------------------------------------------
// Helper
// ---------------------------------------------------------------------------

/**
 * Build a single save-ready AA object with embedded protokolle
 * in `ar_protokolleArray`.
 *
 * Usage:
 * ```ts
 * const aaSaveData = buildNewAAFromFeatures({
 *   team: { id: 5, name: "Team A" },
 *   angelegtVon: "admin",
 *   features: highlightedFeatures,
 * });
 *
 * await updateDataByClassName(jwt, "arbeitsauftrag", aaSaveData);
 * ```
 */
export function buildNewAAFromFeatures(
  input: NewAAInput
): Record<string, unknown> {
  const { team, angelegtVon, features, nummer } = input;
  const now = dayjs();

  // --- Build one protokoll per feature ---
  // Negative IDs: -2, -3, -4, … (new objects, -1 is reserved for the AA)
  const arProtokollArray: Record<string, unknown>[] = [];
  let nextId = -2;

  for (let i = 0; i < features.length; i++) {
    const feature = features[i];
    const sourceLayer = feature.sourceLayer ?? "";
    const fkField = SOURCE_LAYER_TO_FK[sourceLayer];

    if (!fkField) {
      console.warn(
        `[buildNewAAFromFeatures] Unknown sourceLayer "${sourceLayer}", skipping feature`,
        feature
      );
      continue;
    }

    const rawId = feature.properties?.id;
    if (rawId == null) {
      throw new Error(
        `[buildNewAAFromFeatures] Feature at index ${i} (sourceLayer="${sourceLayer}") has no properties.id`
      );
    }
    const featureId = Number(rawId);
    if (!featureId || isNaN(featureId)) {
      throw new Error(
        `[buildNewAAFromFeatures] Feature at index ${i} (sourceLayer="${sourceLayer}") has invalid properties.id: ${String(rawId)}`
      );
    }

    arProtokollArray.push({
      arbeitsprotokoll: {
        id: nextId,
        protokollnummer: i + 1,
        [fkField]: featureId,
        arbeitsprotokollstatus: { id: 1 },
      },
    });

    nextId--;
  }

  // --- Build AA save data (id=-1 signals new object to the server) ---
  return {
    id: -1,
    team: { id: team.id },
    angelegt_von: angelegtVon,
    angelegt_am: now.valueOf(),
    ...(nummer != null ? { nummer } : {}),
    ar_protokolleArray: arProtokollArray,
  };
}
