import dayjs from "dayjs";
import type { LassoSelectedFeature } from "../store/slices/arbeitsauftraege";

// ---------------------------------------------------------------------------
// Source-layer → server FK field mapping
// ---------------------------------------------------------------------------

/** Maps the vector-tile source layer name to the FK field on arbeitsprotokoll. */
const SOURCE_LAYER_TO_FK: Record<string, string> = {
  leuchten: "fk_leuchte",
  standorte: "fk_standort",
  leitungen: "fk_leitung",
  schaltstelle: "fk_schaltstelle",
  abzweigdosen: "fk_abzweigdose",
  mauerlaschen: "fk_mauerlasche",
};

/** Maps the vector-tile source layer name to the internal fachobjekt type key. */
const SOURCE_LAYER_TO_TYPE: Record<string, string> = {
  leuchten: "tdta_leuchten",
  standorte: "tdta_standort_mast",
  leitungen: "leitung",
  schaltstelle: "schaltstelle",
  abzweigdosen: "abzweigdose",
  mauerlaschen: "mauerlasche",
};

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface NewAAInput {
  /** Team FK object */
  team: { id: number; name?: string };
  /** Username of the creator */
  angelegtVon: string;
  /** Features selected from the Fachobjekte map (via lasso or manual pick) */
  features: LassoSelectedFeature[];
  /** Optional AA nummer (auto-generated by server if omitted) */
  nummer?: string;
}

/** A single arbeitsprotokoll save payload (ready for SaveObject endpoint). */
export interface ProtokollSavePayload {
  /** FK field name, e.g. "fk_leuchte" */
  fkField: string;
  /** ID of the referenced fachobjekt */
  fkValue: number;
  /** Internal type key, e.g. "tdta_leuchten" */
  fachobjektType: string;
  /** The full save data object for the server */
  data: Record<string, unknown>;
}

/** The complete result: AA save payload + its protokoll payloads. */
export interface NewAAResult {
  /** Data for `updateDataByClassName(jwt, "arbeitsauftrag", aaSaveData)` */
  aaSaveData: Record<string, unknown>;
  /** Individual protokoll payloads for `updateDataByClassName(jwt, "arbeitsprotokoll", ...)` */
  protokolle: ProtokollSavePayload[];
}

// ---------------------------------------------------------------------------
// Helper
// ---------------------------------------------------------------------------

/**
 * Build save-ready objects for a new Arbeitsauftrag (AA) with one
 * Arbeitsprotokoll per selected Fachobjekt feature.
 *
 * Usage:
 * ```ts
 * const { aaSaveData, protokolle } = buildNewAAFromFeatures({
 *   team: { id: 5, name: "Team A" },
 *   angelegtVon: "admin",
 *   features: lassoSelectedFeatures,
 * });
 *
 * // 1. Create the AA
 * const aaResult = await updateDataByClassName(jwt, "arbeitsauftrag", aaSaveData);
 * const aaId = (aaResult as { id: number }).id;
 *
 * // 2. Create each protokoll linked to the AA
 * for (const p of protokolle) {
 *   await updateDataByClassName(jwt, "arbeitsprotokoll", {
 *     ...p.data,
 *     fk_arbeitsauftrag: aaId,
 *   });
 * }
 * ```
 */
export function buildNewAAFromFeatures(input: NewAAInput): NewAAResult {
  const { team, angelegtVon, features, nummer } = input;
  const now = dayjs();

  // --- Build AA save data (id=-1 signals new object to the server) ---
  const aaSaveData: Record<string, unknown> = {
    id: -1,
    team: { id: team.id },
    angelegt_von: angelegtVon,
    angelegt_am: now.format("YYYY-MM-DDTHH:mm:ss"),
    ...(nummer != null ? { nummer } : {}),
  };

  // --- Build one protokoll per feature ---
  // Negative IDs: -2, -3, -4, … (new objects, -1 is reserved for the AA)
  const protokolle: ProtokollSavePayload[] = [];
  let nextId = -2;

  for (let i = 0; i < features.length; i++) {
    const feature = features[i];
    const sourceLayer = feature.sourceLayer ?? "";
    const fkField = SOURCE_LAYER_TO_FK[sourceLayer];
    const fachobjektType = SOURCE_LAYER_TO_TYPE[sourceLayer];

    if (!fkField || !fachobjektType) {
      console.warn(
        `[buildNewAAFromFeatures] Unknown sourceLayer "${sourceLayer}", skipping feature`,
        feature
      );
      continue;
    }

    const featureId = Number(feature.properties?.id ?? feature.id);
    if (!featureId || isNaN(featureId)) {
      console.warn(
        `[buildNewAAFromFeatures] No valid id for feature, skipping`,
        feature
      );
      continue;
    }

    const data: Record<string, unknown> = {
      id: nextId,
      protokollnummer: i + 1,
      [fkField]: featureId,
      // Default status: "offen" (id=1 / schluessel "0")
      arbeitsprotokollstatus: { id: 1 },
    };

    protokolle.push({
      fkField,
      fkValue: featureId,
      fachobjektType,
      data,
    });

    nextId--;
  }

  return { aaSaveData, protokolle };
}
