import dayjs from "dayjs";

// ---------------------------------------------------------------------------
// Source-layer → server FK field mapping
// ---------------------------------------------------------------------------

/** Maps the vector-tile source layer name to the FK field on arbeitsprotokoll. */
export const SOURCE_LAYER_TO_FK: Record<string, string> = {
  leuchten: "fk_leuchte",
  standorte: "fk_standort",
  leitungen: "fk_leitung",
  schaltstelle: "fk_schaltstelle",
  abzweigdosen: "fk_abzweigdose",
  mauerlaschen: "fk_mauerlasche",
};

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Minimal feature shape needed for AA creation. */
export interface AAFeatureInput {
  sourceLayer?: string;
  properties?: Record<string, unknown>;
}

export interface NewAAInput {
  /** Team FK object */
  team: { id: number; name?: string };
  /** Username of the creator */
  angelegtVon: string;
  /** Highlighted features from the Fachobjekte map */
  features: AAFeatureInput[];
  /** Optional AA nummer (auto-generated by server if omitted) */
  nummer?: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Build AP (Arbeitsprotokoll) entries from highlighted features.
 *
 * Each feature produces one entry in `ar_protokolleArray`.
 * `startProtokollnummer` and `startNegativeId` allow callers to continue
 * numbering after existing protokolle.
 */
export function buildAPEntriesFromFeatures(
  features: AAFeatureInput[],
  startProtokollnummer = 1,
  startNegativeId = -2
): Record<string, unknown>[] {
  const entries: Record<string, unknown>[] = [];
  let nextId = startNegativeId;

  for (let i = 0; i < features.length; i++) {
    const feature = features[i];
    const sourceLayer = feature.sourceLayer ?? "";
    const fkField = SOURCE_LAYER_TO_FK[sourceLayer];

    if (!fkField) {
      console.warn(
        `[buildAPEntriesFromFeatures] Unknown sourceLayer "${sourceLayer}", skipping feature`,
        feature
      );
      continue;
    }

    const rawId = feature.properties?.id;
    if (rawId == null) {
      throw new Error(
        `[buildAPEntriesFromFeatures] Feature at index ${i} (sourceLayer="${sourceLayer}") has no properties.id`
      );
    }
    const featureId = Number(rawId);
    if (!featureId || isNaN(featureId)) {
      throw new Error(
        `[buildAPEntriesFromFeatures] Feature at index ${i} (sourceLayer="${sourceLayer}") has invalid properties.id: ${String(rawId)}`
      );
    }

    entries.push({
      arbeitsprotokoll: {
        id: nextId,
        protokollnummer: startProtokollnummer + i,
        [fkField]: featureId,
        arbeitsprotokollstatus: null,
      },
    });

    nextId--;
  }

  return entries;
}

/**
 * Build a single save-ready AA object with embedded protokolle
 * in `ar_protokolleArray`.
 *
 * Usage:
 * ```ts
 * const aaSaveData = buildNewAAFromFeatures({
 *   team: { id: 5, name: "Team A" },
 *   angelegtVon: "admin",
 *   features: highlightedFeatures,
 * });
 *
 * await updateDataByClassName(jwt, "arbeitsauftrag", aaSaveData);
 * ```
 */
export function buildNewAAFromFeatures(
  input: NewAAInput
): Record<string, unknown> {
  const { team, angelegtVon, features, nummer } = input;
  const now = dayjs();

  const arProtokollArray = buildAPEntriesFromFeatures(features);

  // --- Build AA save data (id=-1 signals new object to the server) ---
  return {
    id: -1,
    team: { id: team.id },
    angelegt_von: angelegtVon,
    angelegt_am: now.valueOf(),
    ...(nummer != null ? { nummer } : {}),
    ar_protokolleArray: arProtokollArray,
  };
}

/**
 * Build an update payload that appends new AP entries (from highlighted
 * features) to an existing Arbeitsauftrag.
 */
export function buildAddFeaturesToAAPayload({
  aaId,
  existingProtokolle,
  features,
}: {
  aaId: number;
  existingProtokolle: Record<string, unknown>[];
  features: AAFeatureInput[];
}): Record<string, unknown> {
  // Find the highest existing protokollnummer
  let maxProtokollnummer = 0;

  // Build minimal references for existing protokolle — only send the id
  // so the server doesn't choke on deeply nested data.
  const existingRefs: Record<string, unknown>[] = [];
  for (const entry of existingProtokolle) {
    const ap = entry.arbeitsprotokoll as
      | Record<string, unknown>
      | undefined;
    const nr = Number(ap?.protokollnummer ?? 0);
    if (nr > maxProtokollnummer) {
      maxProtokollnummer = nr;
    }
    if (ap?.id != null) {
      existingRefs.push({ arbeitsprotokoll: { id: ap.id } });
    }
  }

  const newEntries = buildAPEntriesFromFeatures(
    features,
    maxProtokollnummer + 1,
    -2
  );


  return {
    id: aaId,
    ar_protokolleArray: [...existingRefs, ...newEntries],
  };
}
