import type { MapLibreThreeReferenceSurfacesOptions } from "./MapLibreThreeReferenceSurfacesDemo";
import {
  REFERENCE_ATMOSPHERE_MODE,
  REFERENCE_CAMERA_PRESET,
  REFERENCE_SURFACE,
  TERRAIN_GEOMETRY_MODE,
  TERRAIN_HEIGHT_DATUM,
  WGS84_REFERENCE_AXES,
} from "./maplibre-three-reference-surfaces";

/** Shared defaults; scoped stories override only the variable under comparison. */
export const REFERENCE_SURFACE_DEFAULTS: MapLibreThreeReferenceSurfacesOptions =
  {
    showLocalTangentPlane: false,
    showLocalSphere: false,
    showEllipsoid: false,
    showQuasigeoid: false,
    showTerrain: true,
    showNivellementPoints: false,
    showMesh2024: false,
    referenceRadiusMeters: 12_000,
    referenceOpacity: 0.72,
    referenceVerticalScale: 1,
    referenceVerticalOffsetMeters: 0,
    localSphereRadiusMeters:
      WGS84_REFERENCE_AXES.defaultLocalSphereRadiusMeters,
    terrainGeometryMode: TERRAIN_GEOMETRY_MODE.WGS84_ECEF,
    terrainHeightDatum: TERRAIN_HEIGHT_DATUM.ELLIPSOIDAL,
    terrainModel: "dom1",
    terrainAppearance: "viridis",
    autoElevationRange: false,
    terrainErrorTargetPixels: 2,
    terrainElevationMinimumMeters: 38.95,
    terrainElevationMaximumMeters: 406.51,
    meshErrorTargetPixels: 2,
    meshOpacity: 1,
    meshAppearance: "elevation",
    validationSurface: REFERENCE_SURFACE.TERRAIN,
    validationColorLimitMeters: 2,
    nivellementPointSizePixels: 7,
    longitude: 7.1999207,
    latitude: 51.2725716,
    zoom: 14.5,
    pitch: 55,
    bearing: 22,
    fovDegrees: 36.87,
    showAngularGuideLines: false,
    angularGuideSpacingDegrees: 5,
    cameraPreset: REFERENCE_CAMERA_PRESET.MAP_TARGET,
    atmosphereMode: REFERENCE_ATMOSPHERE_MODE.OFF,
    atmosphereVisibilityKilometers: 120,
    atmosphereScaleHeightMeters: 8_500,
    atmosphereObserverEllipsoidalHeightMeters: 350,
    atmosphereColor: "#b8cbd8",
    showShadowSimulation: false,
    shadowDayOfYear: 52,
    shadowMinutes: 7 * 60 + 40,
    shadowAreaMeters: 4_000,
    softSunShadows: true,
  };
