export const strings = {
  footprintsFlyToImage: "Unverzerrte Bildvorschau starten",
  footprintsOpenImage: "Bild im Browser öffnen",
  footprintsDownloadImage: "Bild direkt herunterladen",
  footprintsRequestReview: "Datenschutzprüfung beantragen",
  previewOpenImage: "Bild im Browser öffnen",
  previewDownloadImage: "Bild herunterladen",
  previewRequestReview: "Datenschutzprüfung beantragen",
  previewClose: "Bildvorschau beenden",
  cubeContainerAria:
    "Ziehen zum Drehen der Kamera; Pfeiltasten links/rechts zum Drehen",
  cubeNorthArrowAria: "Auf Nordausrichtung setzen",
  cubeSelectorNorthAria: "Nord auswählen",
  cubeSelectorSouthAria: "Süd auswählen",
  cubeSelectorEastAria: "Ost auswählen",
  cubeSelectorWestAria: "West auswählen",
  cubeFacadeNorth: "NORD\u200bSEITE",
  cubeFacadeEast: "OST\u200bSEITE",
  cubeFacadeSouth: "SÜD\u200bSEITE",
  cubeFacadeWest: "WEST\u200bSEITE",
  cubeRotateLeftTooltip: "Gegen Uhrzeigersinn drehen",
  cubeRotateRightTooltip: "Im Uhrzeigersinn drehen",
  cubeRotateLeftAria: "Nach links drehen",
  cubeRotateRightAria: "Nach rechts drehen",
  cubeFaceNorthAria: "Nord auswählen (Vorderseite)",
  cubeFaceSouthAria: "Süd auswählen (Rückseite)",
  cubeFaceEastAria: "Ost auswählen (linke Seite)",
  cubeFaceWestAria: "West auswählen (rechte Seite)",
} as const;
