(module
  ;; Exact area-weighted normals: f64 cross products, f32 per-face accumulation.
  (memory (export "memory") 1 2048)
  ;; Three.js BufferGeometry.computeVertexNormals equivalent: cross products
  ;; in f64, f32 accumulation after each triangle, then f64 normalization.
  (func $add (param $p i32) (param $x f64) (param $y f64) (param $z f64)
    (f32.store (local.get $p) (f32.demote_f64 (f64.add (f64.promote_f32 (f32.load (local.get $p))) (local.get $x))))
    (f32.store offset=4 (local.get $p) (f32.demote_f64 (f64.add (f64.promote_f32 (f32.load offset=4 (local.get $p))) (local.get $y))))
    (f32.store offset=8 (local.get $p) (f32.demote_f64 (f64.add (f64.promote_f32 (f32.load offset=8 (local.get $p))) (local.get $z)))))
  (func $load (param $p i32) (result f64) (f64.promote_f32 (f32.load (local.get $p))))
  (func (export "normals") (param $pos i32) (param $idx i32) (param $normal i32) (param $vertices i32) (param $indices i32)
    (local $i i32) (local $a i32) (local $b i32) (local $c i32) (local $pa i32) (local $pb i32) (local $pc i32) (local $p i32)
    (local $ax f64) (local $ay f64) (local $az f64) (local $cx f64) (local $cy f64) (local $cz f64)
    (local $nx f64) (local $ny f64) (local $nz f64) (local $scale f64)
    (memory.fill (local.get $normal) (i32.const 0) (i32.mul (local.get $vertices) (i32.const 12)))
    (loop $tri
      (local.set $p (i32.add (local.get $idx) (i32.mul (local.get $i) (i32.const 4))))
      (local.set $a (i32.mul (i32.load (local.get $p)) (i32.const 12)))
      (local.set $b (i32.mul (i32.load offset=4 (local.get $p)) (i32.const 12)))
      (local.set $c (i32.mul (i32.load offset=8 (local.get $p)) (i32.const 12)))
      (local.set $pa (i32.add (local.get $pos) (local.get $a)))
      (local.set $pb (i32.add (local.get $pos) (local.get $b)))
      (local.set $pc (i32.add (local.get $pos) (local.get $c)))
      (local.set $ax (f64.sub (call $load (local.get $pa)) (call $load (local.get $pb))))
      (local.set $ay (f64.sub (call $load (i32.add (local.get $pa) (i32.const 4))) (call $load (i32.add (local.get $pb) (i32.const 4)))))
      (local.set $az (f64.sub (call $load (i32.add (local.get $pa) (i32.const 8))) (call $load (i32.add (local.get $pb) (i32.const 8)))))
      (local.set $cx (f64.sub (call $load (local.get $pc)) (call $load (local.get $pb))))
      (local.set $cy (f64.sub (call $load (i32.add (local.get $pc) (i32.const 4))) (call $load (i32.add (local.get $pb) (i32.const 4)))))
      (local.set $cz (f64.sub (call $load (i32.add (local.get $pc) (i32.const 8))) (call $load (i32.add (local.get $pb) (i32.const 8)))))
      (local.set $nx (f64.sub (f64.mul (local.get $cy) (local.get $az)) (f64.mul (local.get $cz) (local.get $ay))))
      (local.set $ny (f64.sub (f64.mul (local.get $cz) (local.get $ax)) (f64.mul (local.get $cx) (local.get $az))))
      (local.set $nz (f64.sub (f64.mul (local.get $cx) (local.get $ay)) (f64.mul (local.get $cy) (local.get $ax))))
      (call $add (i32.add (local.get $normal) (local.get $a)) (local.get $nx) (local.get $ny) (local.get $nz))
      (call $add (i32.add (local.get $normal) (local.get $b)) (local.get $nx) (local.get $ny) (local.get $nz))
      (call $add (i32.add (local.get $normal) (local.get $c)) (local.get $nx) (local.get $ny) (local.get $nz))
      (local.set $i (i32.add (local.get $i) (i32.const 3)))
      (br_if $tri (i32.lt_u (local.get $i) (local.get $indices))))
    (local.set $i (i32.const 0))
    (loop $normalize
      (local.set $p (i32.add (local.get $normal) (i32.mul (local.get $i) (i32.const 12))))
      (local.set $nx (call $load (local.get $p)))
      (local.set $ny (call $load (i32.add (local.get $p) (i32.const 4))))
      (local.set $nz (call $load (i32.add (local.get $p) (i32.const 8))))
      (local.set $scale (f64.sqrt (f64.add (f64.add (f64.mul (local.get $nx) (local.get $nx)) (f64.mul (local.get $ny) (local.get $ny))) (f64.mul (local.get $nz) (local.get $nz)))))
      (if (f64.eq (local.get $scale) (f64.const 0)) (then (local.set $scale (f64.const 1))))
      (local.set $scale (f64.div (f64.const 1) (local.get $scale)))
      (f32.store (local.get $p) (f32.demote_f64 (f64.mul (local.get $nx) (local.get $scale))))
      (f32.store offset=4 (local.get $p) (f32.demote_f64 (f64.mul (local.get $ny) (local.get $scale))))
      (f32.store offset=8 (local.get $p) (f32.demote_f64 (f64.mul (local.get $nz) (local.get $scale))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $normalize (i32.lt_u (local.get $i) (local.get $vertices))))
  )
)
