export const LINEAR_SEGMENT_LINE_MODES = {
  DIRECT: "direct",
  COMPONENTS: "components",
} as const;

export const LINEAR_SEGMENT_LINE_MODE_DIRECT = LINEAR_SEGMENT_LINE_MODES.DIRECT;
export const LINEAR_SEGMENT_LINE_MODE_COMPONENTS =
  LINEAR_SEGMENT_LINE_MODES.COMPONENTS;

export type LinearSegmentLineMode =
  (typeof LINEAR_SEGMENT_LINE_MODES)[keyof typeof LINEAR_SEGMENT_LINE_MODES];

export const DEFAULT_LINEAR_SEGMENT_LINE_MODE =
  LINEAR_SEGMENT_LINE_MODES.COMPONENTS;
