export const LINEAR_SEGMENT_LINE_MODE_DIRECT = "direct" as const;
export const LINEAR_SEGMENT_LINE_MODE_COMPONENTS = "components" as const;

export const LINEAR_SEGMENT_LINE_MODES = [
  LINEAR_SEGMENT_LINE_MODE_DIRECT,
  LINEAR_SEGMENT_LINE_MODE_COMPONENTS,
] as const;

export type LinearSegmentLineMode = (typeof LINEAR_SEGMENT_LINE_MODES)[number];

export const DEFAULT_LINEAR_SEGMENT_LINE_MODE =
  LINEAR_SEGMENT_LINE_MODE_COMPONENTS;
