export {
  SELECT_TOOL_TYPE,
  ANNOTATION_TYPE_POINT,
  ANNOTATION_TYPE_DISTANCE,
  ANNOTATION_TYPE_POLYLINE,
  ANNOTATION_TYPE_AREA_GROUND,
  ANNOTATION_TYPE_AREA_PLANAR,
  ANNOTATION_TYPE_AREA_VERTICAL,
  ANNOTATION_TYPE_LABEL,
  LINEAR_SEGMENT_LINE_MODES,
  LINEAR_SEGMENT_LINE_MODE_DIRECT,
  LINEAR_SEGMENT_LINE_MODE_COMPONENTS,
  DEFAULT_LINEAR_SEGMENT_LINE_MODE,
  DEFAULT_POINT_LABEL_METRIC_MODE,
  PLANAR_POLYGON_SOURCE_KINDS,
  isPointAnnotationEntry,
} from "@carma-mapping/annotations/core";

export type {
  AnnotationMode,
  DirectLineLabelMode,
  DistanceRelationLabelVisibilityByKind,
  LinearSegmentLineMode,
  AnnotationGeometryEdge,
  AnnotationGeometryPoint,
  AnnotationLabelAnchor,
  AnnotationLabelAppearance,
  PlanarPolygonSourceKind,
  PlanarPolygonGroup,
  PlanarPolygonGroupVertex,
  PlanarPolygonLocalFrame,
  PlanarPolygonPlane,
  PointDistanceRelation,
  PointLabelMetricMode,
  PointReferenceLineAnnotation,
  ReferenceLineLabelKind,
  AnnotationEntry,
  PointAnnotationEntry,
  AnnotationCollection,
  AnnotationPersistenceEnvelopeV2,
} from "@carma-mapping/annotations/core";
