export const strings = {
  title: "Schrägluftbilder",
  flyToImage: "Flug zum Bild",
  flyToImageTooltip: "Unverzerrte Bildvorschau starten",
  closePreview: "Vorschau beenden",
  closePreviewTooltip: "Bildvorschau beenden",
  openImage: "Bild öffnen",
  openImageTooltip: "Bild im Browser öffnen",
  downloadImage: "Herunterladen",
  downloadImageTooltip: "Bild direkt herunterladen",
  requestReview: "Datenschutzprüfung beantragen",
  rotateLeft: "Gegen den Uhrzeigersinn drehen",
  rotateRight: "Im Uhrzeigersinn drehen",
  loadingData: "Schrägluftbild-Daten werden geladen …",
  noImage: "Kein Bild in der Nähe der Kartenmitte",
  readoutTooltip: "Schrägluftbild-Werkzeuge öffnen",
  controlOn: "Schrägluftbilder einschalten",
  controlOff: "Schrägluftbilder ausschalten",
  sectionImage: "Bild",
  siblingUp: "Nächstes Bild nach vorn",
  siblingDown: "Nächstes Bild nach hinten",
  siblingLeft: "Nächstes Bild nach links",
  siblingRight: "Nächstes Bild nach rechts",
} as const;
