/**
 * Mapped landmark anchors and authored, approximate long-range silhouettes.
 * See README.md for field provenance, uncertainty and separate data licences.
 * These are not surveyed building models or height-validation control points.
 */
import type { GeoreferencedLandmark } from "../base/landmarks";

export const NORDHELLE_LANDMARK_PROVENANCE = {
  capturedAt: "2026-09-14T12:51:14Z",
  osmSnapshotAt: "2026-09-14T12:43:25Z",
  mappedDataAttribution: "© OpenStreetMap contributors",
  mappedDataLicenseUrl: "https://www.openstreetmap.org/copyright",
  groundDataAttribution: "Geobasis NRW",
  groundDataLicenseUrl: "https://www.govdata.de/dl-de/zero-2-0",
  groundDataDocumentationUrl:
    "https://www.bezreg-koeln.nrw.de/geobasis-nrw/produkte-und-dienste/hoehenmodelle/digitale-gelaendemodelle/digitales-gelaendemodell",
  groundGridSpacingMeters: 1,
  coveragePolicy:
    "Ground sampled independently from full NRW DGM1; do not infer coverage of the clipped CARMA Terrarium service.",
  modelAccuracy:
    "Positions are mapped, ground anchors are raster samples, and primitive dimensions are illustrative. Not survey or visibility-analysis ground truth.",
  referenceImage: {
    title: "Nordhelle.JPG",
    author: "Milseburg",
    date: "2011-07-16",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Nordhelle.JPG",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    usage: "Reference only; no bitmap or photo-derived texture bundled.",
  },
} as const;

/**
 * The three tall radio towers, plus the much smaller Robert-Kolb lookout.
 * Geometry proportions are authored approximations; only total heights have
 * the per-object evidence below. Convert H to h with GCG2016 before ECEF use.
 */
export const NORDHELLE_LANDMARKS = [
  {
    id: "wdr-nordhelle",
    name: "WDR Sender Nordhelle",
    longitudeDegrees: 7.7566997,
    latitudeDegrees: 51.1480857,
    heightMeters: 150,
    groundNormalHeightMeters: 662.09,
    positionEvidence: {
      status: "mapped-not-surveyed",
      sourceUrl: "https://www.openstreetmap.org/way/462542377",
      osmVersion: 2,
      osmEditedAt: "2026-05-18T11:57:44Z",
      method: "way-bounds-center",
    },
    heightEvidence: {
      status: "mapped",
      sourceUrl: "https://www.openstreetmap.org/way/462542377",
      conflictingHeightMeters: 130,
      conflictingSourceUrl:
        "https://www.meinerzhagen.de/fileadmin/user_upload/Meinerzhagen/TourismusFreizeit/Freizeitangebote/Sportliches/Wandern/MVG_Wanderbus_Broschuere_2017_WEB.pdf",
    },
    groundEvidence: {
      status: "approximate-terrain",
      source: "nrw-dgm1-wcs",
      verticalDatum: "DHHN2016",
      horizontalCrs: "EPSG:25832",
      sampleMethod: "containing-1m-pixel-center",
      requestBoundsUtm32Meters: [413032, 5667022, 413042, 5667032],
      sampleCenterUtm32Meters: [413037.5, 5667027.5],
      sourceUrl:
        "https://www.wcs.nrw.de/geobasis/wcs_nw_dgm?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=nw_dgm&FORMAT=image%2Ftiff&SUBSET=x%28413032%2C413042%29&SUBSET=y%285667022%2C5667032%29",
    },
    geometryEvidence: "authored-approximate-silhouette",
    parts: [
      {
        baseHeightMeters: 0,
        heightMeters: 76,
        radiusBottomMeters: 4.2,
        radiusTopMeters: 2.2,
        radialSegments: 16,
        color: "#bcbcb4",
      },
      {
        baseHeightMeters: 70,
        heightMeters: 2,
        radiusBottomMeters: 5.4,
        radiusTopMeters: 5.4,
        radialSegments: 16,
        color: "#888a88",
      },
      {
        baseHeightMeters: 76,
        heightMeters: 26,
        radiusBottomMeters: 2.2,
        radiusTopMeters: 1.5,
        radialSegments: 16,
        color: "#e0ded5",
      },
      {
        baseHeightMeters: 86,
        heightMeters: 1.5,
        radiusBottomMeters: 4.5,
        radiusTopMeters: 4.5,
        radialSegments: 16,
        color: "#8c8c86",
      },
      {
        baseHeightMeters: 98,
        heightMeters: 2,
        radiusBottomMeters: 3.5,
        radiusTopMeters: 3.5,
        radialSegments: 16,
        color: "#e1ddd3",
      },
      {
        baseHeightMeters: 102,
        heightMeters: 48,
        radiusBottomMeters: 1.3,
        radiusTopMeters: 0.55,
        radialSegments: 12,
        color: "#eeeae1",
      },
      {
        baseHeightMeters: 109,
        heightMeters: 5,
        radiusBottomMeters: 1.2,
        radiusTopMeters: 1.12,
        radialSegments: 12,
        color: "#ac4f44",
      },
      {
        baseHeightMeters: 124,
        heightMeters: 5,
        radiusBottomMeters: 0.96,
        radiusTopMeters: 0.88,
        radialSegments: 12,
        color: "#ac4f44",
      },
      {
        baseHeightMeters: 139,
        heightMeters: 5,
        radiusBottomMeters: 0.72,
        radiusTopMeters: 0.64,
        radialSegments: 12,
        color: "#ac4f44",
      },
    ],
  },
  {
    id: "nato-nordhelle",
    name: "NATO-Fernmeldeturm Nordhelle",
    longitudeDegrees: 7.7589117,
    latitudeDegrees: 51.1494475,
    heightMeters: 56,
    groundNormalHeightMeters: 656.77,
    positionEvidence: {
      status: "mapped-not-surveyed",
      sourceUrl: "https://www.openstreetmap.org/node/2812442525",
      osmVersion: 4,
      osmEditedAt: "2023-01-11T18:00:38Z",
      method: "node",
    },
    heightEvidence: {
      status: "mapped",
      sourceUrl: "https://www.openstreetmap.org/node/2812442525",
    },
    groundEvidence: {
      status: "approximate-terrain",
      source: "nrw-dgm1-wcs",
      verticalDatum: "DHHN2016",
      horizontalCrs: "EPSG:25832",
      sampleMethod: "containing-1m-pixel-center",
      requestBoundsUtm32Meters: [413189, 5667171, 413199, 5667181],
      sampleCenterUtm32Meters: [413194.5, 5667176.5],
      sourceUrl:
        "https://www.wcs.nrw.de/geobasis/wcs_nw_dgm?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=nw_dgm&FORMAT=image%2Ftiff&SUBSET=x%28413189%2C413199%29&SUBSET=y%285667171%2C5667181%29",
    },
    geometryEvidence: "authored-approximate-silhouette",
    parts: [
      {
        baseHeightMeters: 0,
        heightMeters: 43,
        radiusBottomMeters: 3.5,
        radiusTopMeters: 2.2,
        radialSegments: 16,
        color: "#a6a7a0",
      },
      {
        baseHeightMeters: 34,
        heightMeters: 1.5,
        radiusBottomMeters: 5.4,
        radiusTopMeters: 5.4,
        radialSegments: 16,
        color: "#878a87",
      },
      {
        baseHeightMeters: 41,
        heightMeters: 2,
        radiusBottomMeters: 5.1,
        radiusTopMeters: 5.1,
        radialSegments: 16,
        color: "#caccc6",
      },
      {
        baseHeightMeters: 43,
        heightMeters: 13,
        radiusBottomMeters: 1.1,
        radiusTopMeters: 0.35,
        radialSegments: 12,
        color: "#d8d9d1",
      },
    ],
  },
  {
    id: "ebbegebirge-waldberg",
    name: "Fernmeldeturm Ebbegebirge / Waldbergsender",
    longitudeDegrees: 7.7732476,
    latitudeDegrees: 51.1467095,
    heightMeters: 150,
    groundNormalHeightMeters: 638.4,
    positionEvidence: {
      status: "mapped-not-surveyed",
      sourceUrl: "https://www.openstreetmap.org/node/297576774",
      osmVersion: 10,
      osmEditedAt: "2026-06-30T15:47:18Z",
      method: "node",
    },
    heightEvidence: {
      status: "mapped",
      sourceUrl: "https://www.openstreetmap.org/node/297576774",
    },
    groundEvidence: {
      status: "approximate-terrain",
      source: "nrw-dgm1-wcs",
      verticalDatum: "DHHN2016",
      horizontalCrs: "EPSG:25832",
      sampleMethod: "containing-1m-pixel-center",
      requestBoundsUtm32Meters: [414187, 5666850, 414197, 5666860],
      sampleCenterUtm32Meters: [414192.5, 5666855.5],
      sourceUrl:
        "https://www.wcs.nrw.de/geobasis/wcs_nw_dgm?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=nw_dgm&FORMAT=image%2Ftiff&SUBSET=x%28414187%2C414197%29&SUBSET=y%285666850%2C5666860%29",
    },
    geometryEvidence: "authored-approximate-silhouette",
    parts: [
      {
        baseHeightMeters: 0,
        heightMeters: 72,
        radiusBottomMeters: 6,
        radiusTopMeters: 3.1,
        radialSegments: 16,
        color: "#b7b8b0",
      },
      {
        baseHeightMeters: 68,
        heightMeters: 4,
        radiusBottomMeters: 9.5,
        radiusTopMeters: 9.5,
        radialSegments: 20,
        color: "#9b9c96",
      },
      {
        baseHeightMeters: 72,
        heightMeters: 6,
        radiusBottomMeters: 9.5,
        radiusTopMeters: 8,
        radialSegments: 20,
        color: "#d2d1c8",
      },
      {
        baseHeightMeters: 78,
        heightMeters: 27,
        radiusBottomMeters: 3.1,
        radiusTopMeters: 2,
        radialSegments: 16,
        color: "#b7b8b0",
      },
      {
        baseHeightMeters: 86,
        heightMeters: 1.5,
        radiusBottomMeters: 6,
        radiusTopMeters: 6,
        radialSegments: 16,
        color: "#8d908c",
      },
      {
        baseHeightMeters: 98,
        heightMeters: 1.5,
        radiusBottomMeters: 4.5,
        radiusTopMeters: 4.5,
        radialSegments: 16,
        color: "#8d908c",
      },
      {
        baseHeightMeters: 105,
        heightMeters: 45,
        radiusBottomMeters: 1.45,
        radiusTopMeters: 0.45,
        radialSegments: 12,
        color: "#ebe9df",
      },
      {
        baseHeightMeters: 112,
        heightMeters: 5,
        radiusBottomMeters: 1.31,
        radiusTopMeters: 1.2,
        radialSegments: 12,
        color: "#b65248",
      },
      {
        baseHeightMeters: 127,
        heightMeters: 5,
        radiusBottomMeters: 0.98,
        radiusTopMeters: 0.87,
        radialSegments: 12,
        color: "#b65248",
      },
      {
        baseHeightMeters: 142,
        heightMeters: 5,
        radiusBottomMeters: 0.64,
        radiusTopMeters: 0.53,
        radialSegments: 12,
        color: "#b65248",
      },
    ],
  },
  {
    id: "robert-kolb",
    name: "Robert-Kolb-Turm",
    longitudeDegrees: 7.7561592,
    latitudeDegrees: 51.1484355,
    heightMeters: 18,
    groundNormalHeightMeters: 663.5,
    positionEvidence: {
      status: "mapped-not-surveyed",
      sourceUrl: "https://www.openstreetmap.org/way/462542374",
      osmVersion: 4,
      osmEditedAt: "2020-02-16T16:58:11Z",
      method: "way-bounds-center",
    },
    heightEvidence: {
      status: "municipality-published",
      sourceUrl: "https://www.herscheid.de/freizeit-tourismus/wandern",
    },
    groundEvidence: {
      status: "approximate-terrain",
      source: "nrw-dgm1-wcs",
      verticalDatum: "DHHN2016",
      horizontalCrs: "EPSG:25832",
      sampleMethod: "containing-1m-pixel-center",
      requestBoundsUtm32Meters: [412995, 5667062, 413005, 5667072],
      sampleCenterUtm32Meters: [413000.5, 5667067.5],
      sourceUrl:
        "https://www.wcs.nrw.de/geobasis/wcs_nw_dgm?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=nw_dgm&FORMAT=image%2Ftiff&SUBSET=x%28412995%2C413005%29&SUBSET=y%285667062%2C5667072%29",
    },
    geometryEvidence: "authored-approximate-silhouette",
    parts: [
      {
        baseHeightMeters: 0,
        heightMeters: 13.5,
        radiusBottomMeters: 4,
        radiusTopMeters: 3.4,
        radialSegments: 4,
        color: "#777167",
      },
      {
        baseHeightMeters: 13.5,
        heightMeters: 3,
        radiusBottomMeters: 3.4,
        radiusTopMeters: 3.4,
        radialSegments: 4,
        color: "#575451",
      },
      {
        baseHeightMeters: 16.5,
        heightMeters: 1.5,
        radiusBottomMeters: 3.9,
        radiusTopMeters: 3.6,
        radialSegments: 4,
        color: "#a39c8b",
      },
    ],
  },
] as const satisfies readonly GeoreferencedLandmark[];
